#!/bin/sh

#  ci_post_clone.sh
#  Solstice
#
#  This script runs after Xcode Cloud clones the repository.
#  It generates Secrets.swift from environment variables.

set -e

echo "Generating Secrets.swift..."

SECRETS_FILE="$CI_PRIMARY_REPOSITORY_PATH/Shared/Helpers/Secrets.swift"

if [ -z "$YAPKIT_API_KEY" ]; then
    echo "warning: YAPKIT_API_KEY environment variable is not set"
    YAPKIT_API_KEY="MISSING_API_KEY"
fi

cat > "$SECRETS_FILE" << EOF
//
//  Secrets.swift
//  Zeitgeist
//
//  Auto-generated by ci_post_clone.sh - DO NOT COMMIT
//

import Foundation

enum Secrets {
	static let yapKitAPIKey = "$YAPKIT_API_KEY"
}
EOF

echo "Secrets.swift generated successfully"
